### ISSUE TITLE
How to Run Sample Project?

### ISSUE THREAD

**Issue by chobo2** [danieleli/Swagger.Net#8]
Hi

I am trying to run the sample project but when I try to load up "http://localhost:2961/SwaggerUI/" it errors out

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Swagger.Net
  StackTrace:
       at Swagger.Net.Factories.ModelFactory.<GetAllTypes>b__4(ApiDescription t) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ModelFactory.cs:line 70
       at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Swagger.Net.Factories.ModelFactory.GetAllTypes(IEnumerable`1 apiDescs) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ModelFactory.cs:line 69
       at Swagger.Net.Factories.ModelFactory.GetUniqueTypes(IEnumerable`1 apiDescs) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ModelFactory.cs:line 47
       at Swagger.Net.Factories.ModelFactory.GetModels(IEnumerable`1 apiDescs) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ModelFactory.cs:line 31
       at Swagger.Net.Factories.ApiFactory.CreateApiDeclaration(String rootUrl, HttpControllerDescriptor controller) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ApiFactory.cs:line 75
       at Swagger.Net.Factories.ApiFactory.CreateApiDeclaration(String rootUrl, String controllerName) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\Factories\ApiFactory.cs:line 139
       at Swagger.Net.DocsController.Get(String id) in Downloads\Swagger.Net-master\Swagger.Net-master\Swagger.Net\DocsController.cs:line 72
       at lambda_method(Closure , Object , Object[] )
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters)
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
       at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.<>c__DisplayClass5.<ExecuteAsync>b__4()
       at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)
  InnerException:

**Comment by danieleli** [comment]
Hi, sorry for delay!  Haven't had time to maintain this project.  But it looks like things are going to move forward on the swagger-net/swagger.net repo, which I forked it from.  It might be a couple of weeks before we have a functional build tho. :(.
